apiVersion: v1
kind: ConfigMap
metadata:
  name: conduit-config
  namespace: matrix-conduit
  labels:
    app.kubernetes.io/name: matrix-conduit
    app.kubernetes.io/part-of: kudofools
    app.kubernetes.io/managed-by: flux
data:
  conduit.toml: |
    [global]
    server_name = "conduit.kudofools.dev"
    database_backend = "rocksdb"
    database_path = "/var/lib/matrix-conduit/"
    port = 6167
    address = "0.0.0.0"
    max_request_size = 20_000_000
    allow_registration = true
    allow_federation = true
    allow_check_for_updates = true
    trusted_servers = ["matrix.org"]
    enable_lightning_bolt = true
    turn_uris = ["turn:turn.kudofools.dev:3478?transport=udp", "turn:turn.kudofools.dev:3478?transport=tcp"]

    [global.well_known]
    server = "conduit.kudofools.dev:443"
    client = "https://conduit.kudofools.dev"

    [global.media]
    backend = "filesystem"

    [[global.media.retention]]
    space = "3G"

    [[global.media.retention]]
    scope = "remote"
    accessed = "30d"
    created = "90d"

    [[global.media.retention]]
    scope = "thumbnail"
    space = "512MB"
