apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: conduit-secrets
  namespace: matrix-conduit
  labels:
    app.kubernetes.io/name: matrix-conduit
    app.kubernetes.io/part-of: kudofools
    app.kubernetes.io/managed-by: flux
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: conduit-secrets
    deletionPolicy: Retain
  data:
    - secretKey: registration_token
      remoteRef:
        key: kv/matrix-conduit/secrets
        property: registration_token
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: matrix-conduit-webhook
  namespace: flux-system
  labels:
    app.kubernetes.io/name: matrix-conduit
    app.kubernetes.io/part-of: kudofools
    app.kubernetes.io/managed-by: flux
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: matrix-conduit-webhook
    deletionPolicy: Retain
  data:
    - secretKey: token
      remoteRef:
        key: kv/matrix-conduit/webhook-token
        property: token
