apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: conduit-data-pvc
  namespace: matrix-conduit
  labels:
    app.kubernetes.io/name: matrix-conduit
    app.kubernetes.io/part-of: kudofools
    app.kubernetes.io/managed-by: flux
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi